version: "3"
services:
  jaeger: 
    image: jaegertracing/all-in-one:latest
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
      - 14268:14268
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - 9411:9411    
  otel-collector: 
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml:ro
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "9411"   # Zipkin receiver
      - "55680:55679" # zpages extension
      - "4317:4317" # grpc receiver
    depends_on:
      - jaeger
      - zipkin
  prometheus:
    image: prom/prometheus:latest
    ports:
    - 9090:9090
    command: ["--config.file=/etc/prometheus/prometheus.yml"]
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - otel-collector
    extra_hosts:
      - fibonacci:172.17.0.1
  grafana:
    image: grafana/grafana:latest
    ports:
      - 3001:3000
  mongo:
    image: mongo:latest
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.0
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9300:9300
  graylog:
    image: graylog/graylog:4.0
    ports:
      - 9000:9000
      - 12201:12201/tcp
      - 12201:12201/udp
      - 1514:1514
    environment:
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/